version: '2'

services:
  jenkins:
    container_name: jenkins
    image: bit1/jenkins
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# uncomment next line if you want to keep jenkins data (effectively, all of jenkins) when the container has been deleted
      - jenkins_data:/var/jenkins_home
    privileged: true



volumes:
  jenkins_data:


